kind = "web"
previewPath = "/"
title = "Multiple Disease Predictor"
version = "1.0.0"
id = "artifacts/disease-predictor"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 20695

[services.development]
run = "pnpm --filter @workspace/disease-predictor run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/disease-predictor", "run", "build" ]
publicDir = "artifacts/disease-predictor/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "20695"
BASE_PATH = "/"
